# Generated by Django 2.2.16 on 2022-11-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221123_2049'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='cant_follow_yourself',
        ),
    ]
